### ISSUE TITLE
Enumerations are not supported

### ISSUE THREAD

**Issue by timothyparez** [T0ha/uprotobuf#3]
Consider the following proto definition:

```
syntax = "proto2";

package test;

enum AnimalCategory
{
    AC_INVERTEBRATE = 1;
    AC_FISH = 2;
    AC_AMPHIBIAN = 3;
    AC_REPTILE = 4;
    AC_BIRD = 5;
    AC_MAMMAL = 6;
}

message Animal 
{
    optional string name = 1;
	optional AnimalCategory category = 2;
}
```

This will throw the following exception:

```
import animal_upb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "animal_upb2.py", line 7, in <module>
  File "animal_upb2.py", line 10, in Animal
NameError: name 'AnimalCategory' isn't defined
```

**Comment by rgov** [comment]
Apparently fixed: https://github.com/T0ha/uprotobuf/commit/d5a4c6d3679d4c564baf9db71024f3555dfe8f1d

**Comment by rgov** [comment]
This applies for top-level enums only. The generator code only iterates over the defined message types (`protofile.message_type`) but not defined enum types (`proto_file.enum_type`).

https://github.com/T0ha/uprotobuf/blob/d5a4c6d3679d4c564baf9db71024f3555dfe8f1d/scripts/uprotobuf_plugin.py#L88-L91
